config/routes.rb
Rails.application.routes.draw do
  
  resources :users do
    member do
      get :test_send_mail
    end
  end

  get '/execute_example2_job', to: 'users#execute_example2_job'
  
  root to: 'users#index'
  

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end
  
  def test_send_mail
    @user = User.find(params[:id])
    
    ContractMailer.contracted(@user).deliver_later
    # deliver_now -> sidekiq使わない
    # deliver_later -> sidekiq使う
    
    @message = "成功しました。"
    
    ExampleJob.perform_later
    ExampleJob.set(wait: 10.second).perform_later
    
    # respond_to do |format|
    #   if @user.save
    #     # 保存後にUserMailerを使用してwelcomeメールを送信
    #     UserMailer.with(user: @user).welcome_email.deliver_later
 
    #     format.html { redirect_to(@user, notice: 'ユーザーが正常に作成されました。') }
    #     format.json { render json: @user, status: :created, location: @user }
    #   else
    #     format.html { render action: 'new' }
    #     format.json { render json: @user.errors, status: :unprocessable_entity }
    #   end
    # end
  end
  
  # Herokuにファイルを一時保存できるかどうかの確認
  def execute_example2_job
    Example2Job.perform_later
    redirect_to users_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/index.html.erb
<h1>User一覧</h1>
<table>
  <thead>
    <tr>
      <th>Name</th><th>Email</th><th>Mail</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |u| %>
      <tr>
        <td><%= u.name %></td>
        <td><%= u.email %></td>
        <td style="padding: 5px;">
          <%= link_to "Send a mail", test_send_mail_user_path(u), style: "padding:5px 10px; font-size: 11px; color: white; background-color: #ff69b4; text-decoration: none;" %>
        </td>
      </tr>
    <% end %>
  </tbody>
  
  <%= link_to "Example2を実行", execute_example2_job_path %>
</table>

app/views/users/test_send_mail.html.erb
<p>
  <%= @message %>
</p>